export const STORE_NAME = 'Acme Store'
export const REMAINING = 'REMAINING'
export const ADD_TO_CART = 'ADD TO CART'
export const REMOVE_FROM_CART = 'REMOVE FROM CART'
export const SOLD_OUT = 'SOLD OUT'
