export const STORE_NAME = 'Acme Store'
export const CART_NAME = 'Your Cart'
export const CART_EMPTY = 'Your cart is empty'
export const CART_EMPTY_TIP = 'Please add some products to your cart.'
export const REMAINING = 'REMAINING'
export const ADD_TO_CART = 'ADD TO CART'
export const REMOVE_FROM_CART = 'REMOVE FROM CART'
export const SOLD_OUT = 'SOLD OUT'
